### ISSUE TITLE
How to add more association to login model

### ISSUE THREAD

**Issue by AbonyiXavier** [arifintahu/project-structure-api#6]
I am having an issue adding more relations to login model 

This is how I am adding  just after importing the  Business model 

Login.belongsTo(User, {
  foreignKey: 'user_id'
});

Login.belongsTo(Business, {
  foreignKey: 'business_id'
});

ERROR: relation "business" does not exist 

please assist thanks

**Comment by arifintahu** [comment]
Probably it's because of undefined "business" table, have you created the table and added primary key?

**Comment by AbonyiXavier** [comment]
Yes I have defined the business table with primary key, but throwing that error
